name: projet_parking
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  http: ^0.13.4
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0
  google_maps_flutter: ^2.1.0

dev_dependencies:
  build_runner: ^1.5.0
  pedantic: ^1.7.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
